module.exports = {
	languages: {
		DE: {
			'Actions': 'Aktionen',
			'Account': 'Konto',
			'Add a Private Pad to this Group': 'Ein privates Pad zu dieser Gruppe hinzufügen',
			'Add or remove Users': 'Users hinzufügen entfernen',
			'Add User': 'Nutzer hinzufügen',
			'Cancel': 'Abbrechen',
			'Change Password': 'Passwort ändern',
			'Change Settings': 'Einstellungen ändern',
			'Change': 'Ändern',
			'Click on the group name to switch to the group page.': 'Click on the group name to switch to the group page.',
			'Click on the pad name to switch to the pad page.': 'Click on the pad name to switch to the pad page.',
			'Create a new Group': 'Neue Gruppe erstellen',
			'Create a Public Pad by specific or random name': 'Öffentliches Pad mit gewählten oder zufälligen Namen erstellen',
			'Create Group Pad': 'Gruppen-Pad erstellen',
			'Create Group': 'Gruppe erstellen',
			'Create Groups': 'Gruppen erstellen',
			'Create new Groups and open your recently used Groups': 'Neue Gruppen erstellen oder zuletzt verwendete Gruppen öffnen',
			'Create or open Public Pad. Everyone can see and edit': 'Öffentliches Pad öffnen oder stellen. Alle können einsehen und bearbeiten',
			'Create Public Pad with random name': 'Öffentliches Pad zufälligen Namen erstellen',
			'Create Public Pad': 'Öffentliches Pad erstellen',
			'Create with Random Name': 'Mit zufälligen Namen erstellen',
			'Create': 'Erstellen',
			'Create/Open Public Pads': 'Öffentliches Pad Öffnen/Erstellen',
			'Current Password': 'Aktuelles Passwort',
			'Delete Account': 'Etherpad Konto löschen',
			'Delete Group': 'Gruppe löschen',
			'Delete Pad': 'Pad löschen',
			'Delete': 'Löschen',
			'Deletes all your Pads and Account Data': 'Löscht alle eigenen Pads und Kontodaten',
			'Email address': 'E-Mail-Adresse',
			'Full Name': 'Voller Name',
			'Group Pad': 'Gruppen-Pad',
			'Group Pads': 'Gruppen-Pads',
			'Group': 'Gruppe',
			'Group-Name': 'Gruppen-Name',
			'Groups': 'Gruppen',
			'Help': 'Hilfe',
			'Home': 'Home',
			'I have read and accepted the terms of usage': 'Ich habe die Nutzungsbestimmungen gelesen und akzeptiere diese',
			'Terms of usage': 'Nutzungsbestimmungen',
			'How to create a private pad?': 'How to create a private pad?',
			'If you want to add/invite users, click on the users symbol': 'If you want to add/invite users, click on the users symbol',
			'Intern Pads': 'Interne Pads',
			'Invite': 'Einladen',
			'Last Edit': 'Letzte Änderung',
			'Login Etherpad Account': 'Login Etherpad Konto',
			'Login for Private Group Pads': 'Anmelden für private Gruppen-Pads',
			'Login to create and manage Private Groups Pads': 'Anmelden um private Gruppen zu erstellen/verwalten',
			'Login': 'Anmelden',
			'Logout': 'Abmelden',
			'Manage Group Pads': 'Gruppen-Pads verwalten',
			'Manage Group Users': 'User in der Gruppe verwalten',
			'Manage Groups': 'Gruppen verwalten',
			'Manage Private Pads of this Group': 'Private Pads dieser Gruppe verwalten',
			'Manage your Groups': 'Meine Gruppen verwalten',
			'Manage': 'Verwalten',
			'Make Owner': 'Zum Eigentümer machen',
			'My Groups': 'Meine Gruppen',
			'My Pads': 'Meine Pads',
			'Name': 'Name',
			'Time of last edit': 'Zeitpunkt der letzten Änderung',
			'New Password': 'Neues Passwort',
			'Open a Public Pad by Name': 'Öffentliches Pad per Name öffnen',
			'Open a Public Pad by specific or random name': 'Öffentliches Pad mit zufälligen oder gewählten Name öffnen',
			'Open Groups': 'Gruppen öffnen',
			'Open my recently used Groups': 'Zuletzt verwendete Gruppen öffnen',
			'Open Public Pad with random name': 'Öffentliches Pad mit zufälligen Name öffnen',
			'Open Public Pad': 'Öffentliches Pad öffnen',
			'Open Public Pads': 'Öffentliche Pads öffnen',
			'Open': 'Öffnen',
			'Owner': 'Eigentümer',
			'Username': 'Name',
			'Pad-Name': 'Pad-Name',
			'Password': 'Passwort',
			'Private Group': 'Gruppe',
			'Private Groups': 'Private Gruppen',
			'Password reset': 'Passwort zurücksetzen',
			'Public Pad': 'Öffentliches Pad',
			'Public Pads': 'Öffentliche Pads',
			'Register': 'Registrieren',
			'Remove User': 'Nutzer entfernen',
			'Remove': 'Entfernen',
			'Repeat Password': 'Passwort wiederholen',
			'Repeat New Password': 'Neues Passwort wiederholen',
			'Role': 'Rolle',
			'Search': 'Suche',
			'State': 'Status',
			'There are no pads in this group at the moment.': 'Im Moment sind keine Pads in dieser Gruppe.',
			'There are no users in this group at the moment.': 'Im Moment sind keine Nutzer in dieser Gruppe.',
			'To create a private Pad you first have to create a private Group.': 'Um ein privates Pad anzulegen muss zuerst eine private Gruppe erstellt werden.',
			'User Details': 'Konto Details',
			'User Management': 'Userverwaltung',
			'User Settings': 'Einstellungen',
			'User': 'Nutzer',
			'Users in Group': 'Gruppen-Nutzer',
			'Users': 'Nutzer',
			'You are owner of this group': 'Du bist Eigentümer dieser Gruppe',
			'You are user of this group': 'Du bist Nutzer dieser Gruppe',
			'You have no pads at the moment': 'Sie haben im Moment keine Pads',
			'You have no groups at the moment': 'Sie sind im Moment in keiner Gruppe',
			'': '',
		}
	},
	msgs: {
		REGISTRATION_CLOSED: 'Registration is currently closed.',
		REGISTRATION_COMPLETE: 'Thanks for your registration!',
		NO_PUBLIC_PADS: 'No public pads allowed'
	},
	errors: {
		CONNECTION_ERROR: 'Connection error, please try again',
		MAIL_NOT_CONFIGURED: 'Could not send email. Email sending is not configured.',
		INTERAL_ERROR: 'Internal Error',
		INVALID_REQUEST: 'Invalid Request',
		USER_EXISTS: 'Email address is in use',
		USER_IS_OWNER: 'User is a group owner',
		PASSWORD_WRONG: 'Passwords do not agree',
		USER_OR_PASSWORD_WRONG: 'Invalid user or password',
		USER_INACTIVE: 'User is inactive',
		NO_VALID_MAIL: 'Invalid Email',
		TOO_MANY_REQUESTS: 'Too many request, please contact the system administrator',
		PW_EMPTY: 'Password is empty',
		PAD_EXISTS: 'Pad name already exists',
		PAD_NOT_FOUND: 'Pad not found',
		USER_NOT_LOGGED_IN: 'You are not logged in',
		USER_IS_REGISTERED: 'You are already confirmed',
		USER_NOT_FOUND: 'User not found',
		USER_NOT_CONFIRMED: 'User is not confirmed',
		GROUP_NOT_FOUND: 'Group not found',
		USER_IN_GROUP: 'User is already in Group',
		GROUP_EXISTS: 'Group Name already exists',
		PAD_IN_GROUP: 'Pad already in group',
		INVALID_USER_MAIL: 'Invalid user mail',
		INVALID_USER: 'Invalid User',
		INVALID_PASSWORD: 'Invalid Password',
		INVALID_PAD_NAME: 'Invalid Pad Name',
		INVALID_GROUP_NAME: 'Invalid Group Name',
		INVALID_GROUP_ID: 'Invalid Group ID',
		INVALID_USER_NAME: 'Invalid User Name',
		INVALID_CONFIRMATION_ID: 'Invalid Confirmation ID',
		INVALID_PWRESET_ID: 'Invalid Password Reset ID',
		INVALID_USER_ID: 'Invalid User ID',
		MUST_NOT_BE_OWNER: 'You are owner in one ore more groups. Please give ownership to another user first.',
		MUST_BE_OWNER: 'You must be owner of this group to complete this action',
		MUST_BE_IN_GROUP: 'You must be member of this group to complete this action'
	}
};